# Action to build then push a given Docker image to ECR, creating the
# repository name in ECR first if it does not exist.
name: 'Docker build and deploy to ECR'
description: 'Push Docker image to ECR, creating repository if necessary'
inputs:
  dockerfile-dir:
    description: 'The directory containing the Docker file to build; e.g. "build-dir"'
    required: true
  image-name:
    description: 'The name of the Docker image to push; e.g. "some-image"'
    required: true
  image-version:
    description: 'The version of the Docker image to push; e.g. "1.2.3"'
    required: true
  ecr-registry-path:
    description: 'The path part of the repository name; i.e. the "alpha" in "alpha/docker-image-name"'
    required: true
  aws-region:
    description: 'The AWS region to deploy to'
    required: true
  aws-codeartifact-repository-name:
    description: 'The AWS CodeArtifact repository to be used'
    required: true
  aws-codeartifact-repository-domain:
    description: 'The domain of the AWS CodeArtifact repository to be used'
    required: true
  aws-codeartifact-repository-account:
    description: 'The AWS account ID of the AWS CodeArtifact repository to be used'
    required: true
  pip-url-output-file:
    description: 'Name of file to which pip access URL will be written'
    default: 'pip-url.txt'
    required: false
runs:
  using: "composite"
  steps:
    - name: Get AWS CodeArtifact pip URL
      uses: nationalarchives/da-tre-github-actions/.github/actions/get-aws-codeartifact-pip-url@0.0.2
      with:
        repository: ${{ inputs.aws-codeartifact-repository-name }}
        domain: ${{ inputs.aws-codeartifact-repository-domain }}
        domain-owner: ${{ inputs.aws-codeartifact-repository-account }}
        aws-region: ${{ inputs.aws-region }}
        pip-url-output-file: ${{ inputs.pip-url-output-file }}
    - name: AWS ECR login
      id: aws-ecr-login
      uses: aws-actions/amazon-ecr-login@v1
    - name: Docker build and tag
      shell: bash
      env:
        REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
        REGISTRY_PATH: ${{ inputs.ecr-registry-path }}
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_VERSION: ${{ inputs.image-version }}
        ECR_REPOSITORY_NAME: ${{ inputs.ecr-registry-path }}/${{ inputs.image-name }}
      run: |
        echo "Local file listing follows:"
        ls -la
        echo "SHA256 of pip-url-output-file follows:"
        shasum -a 256 "${{ inputs.pip-url-output-file }}"

        echo "Exporting pip-url-output-file content in PIP_INDEX_URL:"
        export PIP_INDEX_URL="$(cat "${{ inputs.pip-url-output-file }}")"

        echo "SHA256 of PIP_INDEX_URL environment variable follows:"
        echo "${PIP_INDEX_URL}" | shasum -a 256

        docker images
        docker build \
          --build-arg PIP_INDEX_URL \
          --tag "${REGISTRY}/${REGISTRY_PATH}/${IMAGE_NAME}:${IMAGE_VERSION}" \
          "${{ inputs.dockerfile-dir }}"
        docker images
    - name: 'AWS ECR docker push'
      shell: bash
      env:
        REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
        REGISTRY_PATH: ${{ inputs.ecr-registry-path }}
        IMAGE_NAME: ${{ inputs.image-name }}
        IMAGE_TAG: ${{ inputs.image-version }}
        ECR_REPOSITORY_NAME: ${{ inputs.ecr-registry-path }}/${{ inputs.image-name }}
      run: |
        # Create ECR repository if it doesn't exist
        if [[ $(aws ecr describe-repositories \
          --region "${{ inputs.aws-region }}" \
          --repository-names "${ECR_REPOSITORY_NAME}" \
        ) ]]; then
          printf 'Repository "%s" already exists' "${ECR_REPOSITORY_NAME}"
        else
          printf 'Creating repository "%s"' "${ECR_REPOSITORY_NAME}"
          aws ecr create-repository \
            --region "${{ inputs.aws-region }}" \
            --repository-name "${ECR_REPOSITORY_NAME}" \
            --image-scanning-configuration \
            scanOnPush=true
        fi

        docker push "${REGISTRY}/${REGISTRY_PATH}/${IMAGE_NAME}:${IMAGE_TAG}"
