# Action to get latest pushed image
name: 'Get latest deployed'
description: 'Gets the tag of the latest pushed image or 0.0 if no image or latest image not tagged'
inputs:
  ecr_registry_path:
    type: string
    required: true
  aws-role:
    required: true
    description: 'AWS role allowed to read ECR'
outputs:
  latest-version:
    description: latest version
    value: ${{ steps.latest.outputs.latest-version }}
runs:
  using: "composite"
  steps:
    - name: login
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ inputs.aws-role }}
        aws-region: eu-west-2
        role-session-name: role-session-name-${{ github.actor }}-${{ github.triggering_actor }}
    - name: Get latest image details
      id: latest-ecr-version-file
      shell: bash
      run: |
        aws ecr describe-images --repository-name "${{inputs.ecr_registry_path}}" --filter tagStatus=TAGGED --query 'sort_by(imageDetails,& imagePushedAt)[-1]' > ecr_versions.json
        echo "latest-image<<EOF" >> $GITHUB_OUTPUT
        cat ecr_versions.json >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: get latest version
      id: latest
      shell: bash
      run: |
        if ! [ -f ecr_versions.json ]; then
          echo "latest-version=0.0" >> $GITHUB_OUTPUT
        fi
        if [ -f ecr_versions.json ]; then
           echo "latest-version=${{fromJson(steps.latest-ecr-version-file.outputs.latest-image).imageTags[0]}}" >> $GITHUB_OUTPUT
        fi
        if [ -f ecr_versions.json ] && [ "$(grep -c imageTags ecr_versions.json)" > 1 ] && [ ${{fromJson(steps.latest-ecr-version-file.outputs.latest-image).imageTags[0]}} == "latest" ];  then
           echo "latest-version=${{fromJson(steps.latest-ecr-version-file.outputs.latest-image).imageTags[1]}}" >> $GITHUB_OUTPUT ;
        fi
