  name: 'Update-json-value'
  description: Updates and commits a json value to a branch
  inputs:
    file_name:
      type: string
      required: true
    field:
      type: string
      required: true
    value:
      type: string
      required: true
    gpg_private_key:
      type: string
      required: true
    gpg_passphrase:
      type: string
      required: true
    github_token:
      type: string
      required: true
  outputs:
    branch:
      description: branch name containing updated values
      value: ${{ steps.file_commit.outputs.branch }}
  runs:
    using: composite
    steps:
      - name: create_branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@10c7d268152480ae859347db45dc69086cef1d9c
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
        with:
          branch: ${{ inputs.field }}_${{ inputs.value }}
      - name: Checkout branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ inputs.field }}_${{ inputs.value }}
      - name: Update json-values description
        uses: jossef/action-set-json-field@890d7642122dbb2833dddd2003659bb71a2b21fe
        with:
           file: "${{ inputs.file_name }}"
           field: "${{ inputs.field}}"
           value: "${{ inputs.value }}"
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
        with:
            gpg_private_key: ${{ inputs.gpg_private_key }}
            passphrase: ${{ inputs.gpg_passphrase }}
            git_user_signingkey: true
            git_commit_gpgsign: true
      - uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
      - name: pre-commit
        continue-on-error: true
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd
      - name: Commit files
        id: file_commit
        shell: bash
        run: |
         git config --global user.email "${{ steps.import-gpg.outputs.email }}"
         git config --global user.name "${{ steps.import-gpg.outputs.name }}"
         git add -A
         git commit -m "updating ${{ inputs.field }} with ${{ inputs.value }}"
         echo "branch=${{ inputs.field }}_${{ inputs.value }}" >> $GITHUB_OUTPUT
         git push -u origin ${{ inputs.field }}_${{ inputs.value }}
