  name: 'Update-json-value'
  description: Updates and commits a json value to a branch
  inputs:
    file_name:
      type: string
      required: true
    field:
      type: string
      required: true
    value:
      type: string
      required: true
    gpg_private_key:
      type: string
      required: true
    gpg_passphrase:
      type: string
      required: true
    github_token:
      type: string
      required: true
  outputs:
    branch:
      description: branch name containing updated values
      value: ${{ steps.file_commit.outputs.branch }}
  runs:
    using: composite
    steps:
      - name: create_branch
        id: create_branch
        uses: peterjgrainger/action-create-branch@v2.4.0
        env:
          GITHUB_TOKEN: ${{ inputs.github_token }}
        with:
          branch: ${{ inputs.field }}_${{ inputs.value }}
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.field }}_${{ inputs.value }}
      - name: Update json-values description
        uses: jossef/action-set-json-field@v2.1
        with:
           file: "${{ inputs.file_name }}"
           field: "${{ inputs.field}}"
           value: "${{ inputs.value }}"
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
            gpg_private_key: ${{ inputs.gpg_private_key }}
            passphrase: ${{ inputs.gpg_passphrase }}
            git_user_signingkey: true
            git_commit_gpgsign: true
      - name: Commit files
        id: file_commit
        shell: bash
        run: |
         git config --global user.email "${{ steps.import-gpg.outputs.email }}"
         git config --global user.name "${{ steps.import-gpg.outputs.name }}"
         git add -A
         git commit -m "updating ${{ inputs.field }} with ${{ inputs.value }}"
         echo "branch=${{ inputs.field }}_${{ inputs.value }}" >> $GITHUB_OUTPUT
         git push -u origin ${{ inputs.field }}_${{ inputs.value }}
