# Action to get the next version number for a specified repository. An
# optional version suffix can be supplied (e.g. "beta" for "1.2.3-beta")
name: 'Get next version'
description: 'Get the next version number after the latest git tag'
inputs:
  repo-name:
    description: 'The name of the repository to get the latest version for'
    required: true
  version-suffix:
    description: 'Optional version suffix (e.g. "beta" for "1.2.3-beta")'
    required: false
outputs:
  next-version:
    description: The next version for the repository
    value: ${{ steps.next-tag.outputs.next-version }}
runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        REPO_NAME: ${{ inputs.repo-name }}
      run: |
        printf 'github.action_path=%s\n' "${ACTION_PATH}"
        printf '$inputs.repo-name=%s\n' "${REPO_NAME}"
        # The following cd command does not persist across steps
        cd "${ACTION_PATH}"
        pip install --requirement requirements.txt
    - name: 'Get next version for repository "${{ inputs.repo-name }}"'
      id: next-tag
      shell: python
      env:
        PYTHONPATH: ${{ github.action_path }}
        INPUT_REPO_NAME: ${{ inputs.repo-name }}
        INPUT_VERSION_SUFFIX: ${{ inputs.version-suffix }}
      run: |
        import os
        from get_next_version import get_next_version

        next_version = get_next_version(
            repo_name=os.environ['INPUT_REPO_NAME'],
            version_suffix=os.environ['INPUT_VERSION_SUFFIX']
        )

        # Save step output values in GitHub's step output file
        with open(os.getenv('GITHUB_OUTPUT'), 'a') as f:
            f.write(f'next-version={next_version}')
