# Action to log in to AWS CodeArtifact; saves pip/pypi access URL to named file.
name: 'AWS CodeArtifact Repository Login'
description: 'Log in to an AWS CodeArtifact repository'
inputs:
  repository:
    description: 'The AWS CodeArtifact repository name; e.g. "example-repo"'
    required: true
  domain:
    description: 'The AWS CodeArtifact repository domain; e.g. "example-domain"'
    required: true
  domain-owner:
    description: 'The AWS CodeArtifact domain owner (typically AWS account ID)'
    required: true
  auth-token-duration:
    description: 'Seconds until generated auth token expires'
    default: '900'
    required: false
  aws-region:
    description: 'The AWS region in which the CodeArtifact repository resides'
    required: true
runs:
  using: "composite"
  steps:
    - name: AWS CodeArtifact login
      id: get-pip-index-url
      shell: bash
      run: |
        CA_AUTH_TOKEN="$( \
          aws codeartifact get-authorization-token \
          --duration "${{ inputs.auth-token-duration }}" \
          --domain "${{ inputs.domain }}" \
          --domain-owner "${{ inputs.domain-owner }}" \
          --query authorizationToken \
          --output text \
        )"

        echo "pip_index_url=https://${{ inputs.pypi-url-username }}:${CA_AUTH_TOKEN}@${{ inputs.domain }}-${{ inputs.domain-owner }}.d.codeartifact.${{ inputs.aws-region }}.amazonaws.com/pypi/${{ inputs.repository }}/simple/" >> $GITHUB_OUTPUT
