# Action to log in to AWS CodeArtifact.
name: 'AWS CodeArtifact Repository Login'
description: 'Log in to an AWS CodeArtifact repository'
inputs:
  tool:
    description: 'The tool to configure; e.g. "pip"'
    default: 'pip'
    required: false
  repository:
    description: 'The AWS CodeArtifact repository name; e.g. "example-repo"'
    required: true
  domain:
    description: 'The AWS CodeArtifact repository domain; e.g. "example-domain"'
    required: true
  domain-owner:
    description: 'The AWS CodeArtifact domain owner (typically AWS account ID)'
    required: true
  aws-region:
    description: 'The AWS region in which the CodeArtifact repository resides'
    required: true
  role-to-assume:
    description: 'The AWS role for authentication'
    required: true
runs:
  using: "composite"
  steps:
    - name: AWS credential setup
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
        # triggering-actor could differ for re-runs: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        role-session-name: role-session-name-${{ github.actor }}-${{ github.triggering_actor }}
    - name: AWS CodeArtifact login
      shell: bash
      run: |
        aws codeartifact login \
          --tool ${{ inputs.tool }} \
          --repository ${{ inputs.repository }} \
          --domain ${{ inputs.domain }} \
          --domain-owner ${{ inputs.domain-owner }} \
          --region ${{ inputs.aws-region }}
