name: 'Run system tests'
description: 'Run system tests for environment'
inputs:
  source_role:
    description: The management role for the action to assume
  target_role:
    description: The testing role for the management role to assume
  testing_ssh_key:
    description: SSH key for checking out systems testing repo
    required: true
runs:
  using: "composite"
  steps:
  - uses: aws-actions/configure-aws-credentials@v3
    with:
      role-to-assume: ${{ inputs.source_role }}
      aws-region: eu-west-2
  - uses: aws-actions/configure-aws-credentials@v3
    with:
      role-to-assume: ${{ inputs.target_role }}
      aws-region: eu-west-2
      role-chaining: true
      role-skip-session-tagging: true
  - run:  aws sts get-caller-identity
    shell: bash
  - uses: actions/checkout@v3
    with:
      ssh-key: ${{ inputs.testing_ssh_key }}
      repository: nationalarchives/da-tre-system-testing
      ref: main
  - run: ls -lR
    shell: bash
  - uses: coursier/setup-action@v1
  - run: sbt test
    shell: bash
    env:
      ENV: pte-ah
