name: 'Run system tests'
description: 'Run system tests for environment'
inputs:
  environment:
    description: Github environment to use
    required: true
  source_role:
    description: The management role for the action to assume
  target_role:
    description: The testing role for the management role to assume
  testing_environment:
    description: The prefix for the environment you would like to test in
runs:
  using: "composite"
  env:
    ENV: ${{ inputs.testing_environment }}
  steps:
  - uses: aws-actions/configure-aws-credentials@v2
    with:
      role-to-assume: ${{ inputs.source_role }}
      aws-region: eu-west-2
  - uses: aws-actions/configure-aws-credentials@main
    with:
      role-to-assume: ${{ inputs.target_role }}
      aws-region: eu-west-2
      role-chaining: true
      role-skip-session-tagging: true
  - run:  aws sts get-caller-identity
  - uses: actions/checkout@v3
    with:
      repository: nationalarchives/da-tre-system-testing
      ssh-key: ${{ secrets.TESTING_PRIVATE_KEY }}
  - run: ls -lR
  - uses: coursier/setup-action@v1
  - run: sbt test
