# Gets next git version tag, builds and deploys Docker image to ECR; if
# successful, tags git with new version.
name: docker-build-and-ecr-deploy
on:
  workflow_call: # Define inputs to be passed from calling workflow
    inputs: # Name of created Docker image (version will be next git tag version)
      docker_image_name:
        type: string
        required: true
      # Dockerfile's directory
      build_dir:
        type: string
        required: true
      # ECR registry path (i.e. "foo" in "foo/docker-image-name")
      ecr_registry_path:
        type: string
        required: true
      pip_url_output_file:
        type: string
        description: 'Name of file to which pip access URL will be written'
        default: 'pip-url.txt'
        required: false
    # Define secrets to be passed from calling workflow
    secrets:
      AWS_OPEN_ID_CONNECT_ROLE_ARN:
        required: true
      AWS_CODEARTIFACT_REPOSITORY_NAME:
        required: true
      AWS_CODEARTIFACT_REPOSITORY_DOMAIN:
        required: true
      AWS_CODEARTIFACT_REPOSITORY_ACCOUNT:
        required: true
      AWS_REGION:
        required: true
      WIZ_CLIENT_ID:
        required: true
      WIZ_CLIENT_SECRET:
        required: true
      WIZ_PROJECT_TRE:
        required: true

permissions:
  id-token: write  # required by aws-actions/configure-aws-credentials
  contents: write  # to push new git tag
jobs:
  build-deploy-and-tag-ecr-image:
    runs-on: ubuntu-latest
    steps:
      - name: Diagnostic info
        run: |
          printf 'github.event.repository.name=%s\n' "${{ github.event.repository.name }}"
          printf 'github.api_url=%s\n' "${{ github.api_url }}"
          printf 'inputs.python_version=%s\n' "${{ inputs.python_version }}"
      - name: Checkout current
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Get the version to use to tag this build
        id: build-tag
        uses: nationalarchives/da-tre-github-actions/.github/actions/get-next-version@0.0.48
        with:
          repo-name: ${{ github.event.repository.name }}
      - name: Diagnostic info
        run: |
          printf 'steps.build-tag.outputs.next-version=%s\n' "${{ steps.build-tag.outputs.next-version }}"
      - name: AWS credential setup
        uses: aws-actions/configure-aws-credentials@f24d7193d98baebaeacc7e2227925dd47cc267f5
        with:
          role-to-assume: ${{ secrets.AWS_OPEN_ID_CONNECT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          # triggering-actor could differ for re-runs: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          role-session-name: role-session-name-${{ github.actor }}-${{ github.triggering_actor }}
      - name: Save AWS CodeArtifact pip URL to file
        uses: nationalarchives/da-tre-github-actions/.github/actions/get-aws-codeartifact-pip-url@0.0.48
        with:
          repository: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_NAME }}
          domain: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_DOMAIN }}
          domain-owner: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}
          pip-url-output-file: ${{ inputs.pip_url_output_file }}
      - name: Build and push Docker image to AWS ECR
        uses: nationalarchives/da-tre-github-actions/.github/actions/docker-build-and-deploy-to-ecr@0.0.48
        with:
          dockerfile-dir: ${{ inputs.build_dir }}
          image-name: ${{ inputs.docker_image_name }}
          image-version: ${{ steps.build-tag.outputs.next-version }}
          ecr-registry-path: ${{ inputs.ecr_registry_path }}
          aws-region: ${{ secrets.AWS_REGION }}
          pip-index-file: ${{ inputs.pip_url_output_file }}
          wiz-client-id: ${{ secrets.WIZ_CLIENT_ID }}
          wiz-client-secret: ${{ secrets.WIZ_CLIENT_SECRET }}
          wiz-project-tre: ${{ secrets.WIZ_PROJECT_TRE }}
      - name: Add Git tag for this build
        run: |
          git tag ${{ steps.build-tag.outputs.next-version }}
          git push origin ${{ steps.build-tag.outputs.next-version }}
