# Gets next git version tag, builds and deploys Docker image to ECR; if
# successful, tags git with new version.
name: docker-build-and-ecr-deploy-with-wiz-scan
on:
  workflow_call: # Define inputs to be passed from calling workflow
    inputs: # Name of created Docker image (version will be next git tag version)
      docker_image_name:
        type: string
        required: true
      # Dockerfile's directory
      build_dir:
        type: string
        required: true
      # ECR registry path (i.e. "foo" in "foo/docker-image-name")
      ecr_registry_path:
        type: string
        required: true
    secrets:
      AWS_OPEN_ID_CONNECT_ROLE_ARN:
        required: true
      AWS_REGION:
        required: true
      WIZ_CLIENT_ID:
        required: true
      WIZ_CLIENT_SECRET:
        required: true
      WIZ_PROJECT_TRE:
        required: true
permissions:
  id-token: write # required by aws-actions/configure-aws-credentials
  contents: write # to push new git tag
jobs:
  build-deploy-and-tag-ecr-image:
    runs-on: ubuntu-latest
    env:
      WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
      WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
    steps:
      - name: Diagnostic info
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          API_URL: ${{ github.api_url }}
        run: |
          printf 'github.event.repository.name=%s\n' "${REPO_NAME}"
          printf 'github.api_url=%s\n' "${API_URL}"
      - name: Checkout current
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Get the version to use to tag this build
        id: build-tag
        uses: nationalarchives/da-tre-github-actions/.github/actions/get-next-version@110559c0bbef60ed4a81ff8f66f22f1bcef67fd6 # 0.0.82
        with:
          repo-name: ${{ github.event.repository.name }}
      - name: Diagnostic info
        env:
          NEXT_VERSION: ${{ steps.build-tag.outputs.next-version }}
        run: |
          printf 'steps.build-tag.outputs.next-version=%s\n' "${NEXT_VERSION}"
      - name: AWS credential setup
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.2.0
        with:
          role-to-assume: ${{ secrets.AWS_OPEN_ID_CONNECT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: role-session-name-${{ github.actor }}-${{ github.triggering_actor }}
      - name: AWS ECR login
        id: aws-ecr-login
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076
      - name: Docker build and tag
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
          ECR_REGISTRY_PATH: ${{ inputs.ecr_registry_path }}
          DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
          NEXT_VERSION: ${{ steps.build-tag.outputs.next-version }}
          BUILD_DIR: ${{ inputs.build_dir }}
        run: |
          docker buildx build --output=type=docker --provenance=false --sbom=false -f Dockerfile \
          --tag "${ECR_REGISTRY}/${ECR_REGISTRY_PATH}/${DOCKER_IMAGE_NAME}:${NEXT_VERSION}" \
          "${BUILD_DIR}"
          docker images
      - name: Download Wiz CLI
        run: |
          curl -Lo wizcli https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64
          curl -Lo /tmp/wizcli-sha256 https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256
          curl -Lo /tmp/wizcli-sha256.sig https://downloads.wiz.io/v1/wizcli/latest/wizcli-linux-amd64-sha256.sig
          chmod +x wizcli
      - name: Verify Wiz CLI signature
        run: |
          curl -Lo public_key.asc https://downloads.wiz.io/wizcli/public_key.asc
          gpg --import public_key.asc
          gpg --verify /tmp/wizcli-sha256.sig /tmp/wizcli-sha256
          echo "$(cat /tmp/wizcli-sha256) wizcli" | sha256sum --check
      - name: Run Wiz CLI directory scan
        env:
          DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
          RUN_NUMBER: ${{ github.run_number }}
          WIZ_PROJECT_TRE: ${{ secrets.WIZ_PROJECT_TRE }}
        run: >-
          ./wizcli scan dir .
          --name "${DOCKER_IMAGE_NAME}-${RUN_NUMBER}" --project "${WIZ_PROJECT_TRE}"
      - name: Wiz Container Image Scan
        env:
          ECR_REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
          ECR_REGISTRY_PATH: ${{ inputs.ecr_registry_path }}
          DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
          NEXT_VERSION: ${{ steps.build-tag.outputs.next-version }}
          WIZ_PROJECT_TRE: ${{ secrets.WIZ_PROJECT_TRE }}
        run: >-
          ./wizcli scan container-image "${ECR_REGISTRY}/${ECR_REGISTRY_PATH}/${DOCKER_IMAGE_NAME}:${NEXT_VERSION}"
          --project "${WIZ_PROJECT_TRE}"
      - name: 'AWS ECR docker push'
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
          ECR_REGISTRY_PATH: ${{ inputs.ecr_registry_path }}
          DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
          NEXT_VERSION: ${{ steps.build-tag.outputs.next-version }}
        run: |
          docker push "${ECR_REGISTRY}/${ECR_REGISTRY_PATH}/${DOCKER_IMAGE_NAME}:${NEXT_VERSION}"
      - name: Add Git tag for this build
        env:
          NEXT_VERSION: ${{ steps.build-tag.outputs.next-version }}
        run: |
          git tag "${NEXT_VERSION}"
          git push origin "${NEXT_VERSION}"
      - name: Wiz Docker Tag
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
          ECR_REGISTRY: ${{ steps.aws-ecr-login.outputs.registry }}
          ECR_REGISTRY_PATH: ${{ inputs.ecr_registry_path }}
          DOCKER_IMAGE_NAME: ${{ inputs.docker_image_name }}
          NEXT_VERSION: ${{ steps.build-tag.outputs.next-version }}
        run: |
          ./wizcli tag "${ECR_REGISTRY}/${ECR_REGISTRY_PATH}/${DOCKER_IMAGE_NAME}:${NEXT_VERSION}"
