permissions:
  id-token: write
  contents: read
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      scm_vars_file:
        description: Path of tfvars to use
        required: true
        type: string
        default: "hello"
      repository_name:
        description: name of repository
        required: true
        type: string
        default: "nationalarchives/tna-judgments-parser"
      ecr_registry_path:
        type: string
        required: true
        default: "lambda_functions/tre-run-judgment-parser"
      environment:
        type: string
        required: true
        default: "test"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  check_version:
    # environment: ${{ inputs.environment }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Check version
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks latest tag in repository
      - name: Get latest repository tag
        uses: oprypin/find-latest-tag@v1
        id: latest_tag
        with:
          repository: ${{ inputs.repository_name }}
      - run: |
          echo "tna-judgments-parser is at version ${{ steps.latest_tag.outputs.tag }}"
      - name: Get latest ecr
        uses: aws-actions/configure-aws-credentials@v1
        with:
            role-to-assume: ${{ secrets.AWS_OPEN_ID_CONNECT_ROLE_ARN }}
            aws-region: eu-west-2
            role-session-name: role-session-name-${{ github.actor }}-${{ github.triggering_actor }}
      - run: |
              aws ecr list-images \
              --repository-name="lambda_functions/tre-run-judgment-parser" \
              --filter tagStatus=TAGGED
