# Gets next git version tag, builds and deploys Docker image to ECR; if
# successful, tags git with new version.
name: docker-build-and-ecr-deploy
on:
  workflow_call:
    # Define inputs to be passed from calling workflow
    inputs:
      # Name of created Docker image (version will be next git tag version)
      docker_image_name:
        type: string
        required: true
      # Dockerfile's directory
      build_dir:
        type: string
        required: true
      # ECR registry path (i.e. "foo" in "foo/docker-image-name")
      ecr_registry_path:
        type: string
        required: true
    # Define secrets to be passed from calling workflow
    secrets:
      AWS_OPEN_ID_CONNECT_ROLE_ARN:
        required: true
      AWS_CODEARTIFACT_REPOSITORY_NAME:
        required: true
      AWS_CODEARTIFACT_REPOSITORY_DOMAIN:
        required: true
      AWS_CODEARTIFACT_REPOSITORY_ACCOUNT:
        required: true
      AWS_REGION:
        required: true
permissions:
  id-token: write  # required by aws-actions/configure-aws-credentials
  contents: write  # to push new git tag
jobs:
  build-deploy-and-tag-ecr-image:
    runs-on: ubuntu-latest
    steps:
      - name: Diagnostic info
        run: |
          printf 'github.event.repository.name=%s\n' "${{ github.event.repository.name }}"
          printf 'github.api_url=%s\n' "${{ github.api_url }}"
          printf 'inputs.python_version=%s\n' "${{ inputs.python_version }}"
      - name: Checkout current
        uses: actions/checkout@v3
      - name: Get the version to use to tag this build
        id: build-tag
        uses: nationalarchives/da-tre-github-actions/.github/actions/get-next-version@0.0.1
        with:
          repo-name: ${{ github.event.repository.name }}
      - name: Diagnostic info
        run: |
          printf 'steps.build-tag.outputs.next-version=%s\n' "${{ steps.build-tag.outputs.next-version }}"
      - name: AWS credential setup
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_OPEN_ID_CONNECT_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          # triggering-actor could differ for re-runs: https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          role-session-name: role-session-name-${{ github.actor }}-${{ github.triggering_actor }}
      - name: Get AWS CodeArtifact pip URL
        uses: nationalarchives/da-tre-github-actions/.github/actions/get-aws-codeartifact-pip-url@feature/DTE-822-github-workflows-with-and-without-codeartifact
        with:
          repository: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_NAME }}
          domain: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_DOMAIN }}
          domain-owner: ${{ secrets.AWS_CODEARTIFACT_REPOSITORY_ACCOUNT }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Diagnostic info
        run: |
          printf 'steps.get-pip-index-url.outputs.pip_index_url%s\n' "${{ steps.get-pip-index-url.outputs.pip_index_url }}"
      - name: Build and push Docker image to AWS ECR
        uses: nationalarchives/da-tre-github-actions/.github/actions/docker-build-and-deploy-to-ecr@feature/DTE-822-github-workflows-with-and-without-codeartifact
        with:
          dockerfile-dir: ${{ inputs.build_dir }}
          image-name: ${{ inputs.docker_image_name }}
          image-version: ${{ steps.build-tag.outputs.next-version }}
          ecr-registry-path: ${{ inputs.ecr_registry_path }}
          aws-region: ${{ secrets.AWS_REGION }}
          docker-build-arg: ${{ steps.get-pip-index-url.outputs.pip_index_url }}
      - name: Add Git tag for this build
        run: |
          git tag ${{ steps.build-tag.outputs.next-version }}
          git push origin ${{ steps.build-tag.outputs.next-version }}
