

name: repo-check-docker-build-ecr-deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      repository_name:
        description: name of repository
        required: true
        type: string
